### ISSUE TITLE
Error when download episodes by URL

### ISSUE THREAD

**Issue by div4r4k** [ozora-ogino/spotify_dlx#3]
Hello, when I try to download a podcast episode:

python -m spotify_dlx --url https://open.spotify.com/episode/5VuvyaZYeAScvVD0j5QIlr?si=469a5b9ef42c432b

I get this:

Credentials are loaded from cache✨
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\robotina\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_dlx\__main__.py", line 100, in <module>
    _main()
  File "C:\Users\robotina\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_dlx\__main__.py", line 90, in _main
    client.download_from_url(args.url)
  File "C:\Users\robotina\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_dlx\spotify_dlx.py", line 132, in download_from_url
    episode_url = verify_url_pattern(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\robotina\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_dlx\utils.py", line 39, in verify_url_pattern
    return (uri if uri is not None else url).group(groupkey)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: no such group

Running on Win10, Python 3.11.3

**Comment by fedeD84** [comment]
Same issue on MacOS 13.5.2, Python 3.11

**Comment by Foxxey** [comment]
Same issue on Windows 11 Pro (Version 24H2, OS Build 26063.1), Python 3.12.1

**Comment by vieirinhaabr** [comment]
Look at version of the lib, was fixed on https://github.com/ozora-ogino/spotify_dlx/pull/2
